POST http://localhost:5000/api/v1/auth/register
content-type: application/json

{
    "username": "calvin1234",
    "password": "calvin1234",
    "confirmPassword": "calvin1234"
}

###

POST http://localhost:5000/api/v1/auth/login
content-type: application/json

{
    "username": "calvin1234",
    "password": "calvin1234"
}

###

POST http://localhost:5000/api/v1/auth/verify-token
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzMjJlNTFiZTFlY2ZlMDhmNjE0NTAxOSIsImlhdCI6MTY2MzU2MDI2MCwiZXhwIjoxNjYzNjQ2NjYwfQ.BJxgNz6YvGNYwAFCpEbaNcEO_3Wg3MZSxe94TYuT2Kg

###

GET  http://localhost:5000/api/v1/boards
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzMjJlNTFiZTFlY2ZlMDhmNjE0NTAxOSIsImlhdCI6MTY2NDE2MDM5NiwiZXhwIjoxNjY0MjQ2Nzk2fQ.zeiLGzm2MfCGIlMAtY-B4_l5DEubYNXMg5kjhdcRQeY

###

POST  http://localhost:5000/api/v1/boards
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzMjJlNTFiZTFlY2ZlMDhmNjE0NTAxOSIsImlhdCI6MTY2NDE2MDM5NiwiZXhwIjoxNjY0MjQ2Nzk2fQ.zeiLGzm2MfCGIlMAtY-B4_l5DEubYNXMg5kjhdcRQeY

###

GET  http://localhost:5000/api/v1/boards/6329535bcb2fcba6106fb513
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzMjJlNTFiZTFlY2ZlMDhmNjE0NTAxOSIsImlhdCI6MTY2NDE2MDM5NiwiZXhwIjoxNjY0MjQ2Nzk2fQ.zeiLGzm2MfCGIlMAtY-B4_l5DEubYNXMg5kjhdcRQeY

###

PUT  http://localhost:5000/api/v1/boards/63295e6d100335d0f59a43fb
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzMjJlNTFiZTFlY2ZlMDhmNjE0NTAxOSIsImlhdCI6MTY2NDE2MDM5NiwiZXhwIjoxNjY0MjQ2Nzk2fQ.zeiLGzm2MfCGIlMAtY-B4_l5DEubYNXMg5kjhdcRQeY

###

DELETE  http://localhost:5000/api/v1/boards/6329535bcb2fcba6106fb513/sections/633110f69cf67ea952b14411
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzMjJlNTFiZTFlY2ZlMDhmNjE0NTAxOSIsImlhdCI6MTY2NDE2MDM5NiwiZXhwIjoxNjY0MjQ2Nzk2fQ.zeiLGzm2MfCGIlMAtY-B4_l5DEubYNXMg5kjhdcRQeY

### 

PUT  http://localhost:5000/api/v1/boards/6329535bcb2fcba6106fb513/sections/633110f49cf67ea952b14409
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzMjJlNTFiZTFlY2ZlMDhmNjE0NTAxOSIsImlhdCI6MTY2NDE2MDM5NiwiZXhwIjoxNjY0MjQ2Nzk2fQ.zeiLGzm2MfCGIlMAtY-B4_l5DEubYNXMg5kjhdcRQeY

{
    "title": "mandi"
}

###

POST http://localhost:5000/api/v1/products
content-type: application/json

{
    "title": ""
}

###

PATCH  http://localhost:5000/api/v1/products/631b831760efc522837da2a4
content-type: application/json

{
    "title": "minum",
    "completed": true
}

###

DELETE  http://localhost:5000/api/v1/products/63200f687b7095394f846bb1

###